version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: habit_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit_net

  redis:
    image: redis:7-alpine
    container_name: habit_redis
    restart: always
    networks:
      - habit_net

  app:
    image: 212.22.70.98:5000/habit_tracker/app:latest
    container_name: habit_app
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - habit_net


  nginx:
    image: 212.22.70.98:5000/habit_tracker/nginx:latest
    container_name: habit_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
    networks:
      - habit_net

volumes:
  postgres_data:
  static_volume:

networks:
  habit_net:
    driver: bridge
