[pytest]
DJANGO_SETTINGS_MODULE = habit_tracker.settings
python_files = tests_*.py *_tests.py

addopts = --nomigrations --reuse-db --cov --cov-report term-missing --cov-fail-under=80
DJANGO_SETTINGS_MODULE = habit_tracker.settings

[coverage:run]
omit =
    */migrations/*
    */venv/*
    # ✅ ДОБАВИТЬ ЭТОТ ПУТЬ
    habit_tracker/wsgi.py
    habit_tracker/asgi.py

# Убрали: --cov-exclude=...
addopts =
    --cov=.
    --cov-report=xml
    --cov-report=html
    --cov-fail-under=80

[flake8]
max-line-length = 119
exclude =
    .git,
    __pycache__,
    */migrations/*,
    venv/,
    env/