events {
    worker_connections 1024;
}

http {
    upstream habit_tracker {
        # 'app' - это имя сервиса из docker-compose.yml
        server app:8000;
    }

    server {
        listen 80;
        server_name localhost; # Замените на ваш домен в production
        charset utf-8;

        location /static/ {
            alias /app/static/;
        }

        location /media/ {
            alias /app/media/;
        }

        location / {
            proxy_pass http://habit_tracker;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }
}